### ISSUE TITLE
isReorderTestJUnit5Jupiter incorrectly filters out Tests

### ISSUE THREAD

**Issue by cfraenkel** [seregamorph/spring-test-smart-context#7]
The logic of [`com.github.seregamorph.testsmartcontext.SmartDirtiesTestsSorter#isReorderTestJUnit5Jupiter` ](https://github.com/seregamorph/spring-test-smart-context/blob/master/spring-test-smart-context/src/main/java/com/github/seregamorph/testsmartcontext/SmartDirtiesTestsSorter.java#L183-L186) does not correctly consider all `ExtendWith` annotations. If the Test class uses `@ExtendWith` + an annotation that is meta-annotated with ExtendWith (e.g. `@SpringBootTest` then the logic can find the ExtendWith on the class and ignore the meta-annotated version.

Example:
```java
@SpringBootTest
@ExtendWith(OutputCaptureExtension.class)
class ExampleTest{

  @Test
  void someTest(CapturedOutput output) {
//...
  }
}
```

I've debugged the logic and calling `AnnotatedElementUtils#findAllMergedAnnotations`  instead of `AnnotatedElementUtils#findMergedAnnotation` shows the annotation containing `SpringExtension` too.
![image](https://github.com/user-attachments/assets/17583345-5859-46c7-8f15-0e517efbafae)

Corresponding exception:
```
java.lang.IllegalStateException: classOrderStateMap is not defined for class class com.github.seregamorph.testsmartcontext.demo.ExtendWithTest, it means that it was skipped on initial analysis. Discovered classes: [class com.github.seregamorph.testsmartcontext.demo.Integration1Test, class com.github.seregamorph.testsmartcontext.demo.Integration2Test, class com.github.seregamorph.testsmartcontext.demo.NoBaseClass1IntegrationTest, class com.github.seregamorph.testsmartcontext.demo.NoBaseClass2IntegrationTest, class com.github.seregamorph.testsmartcontext.demo.SampleIntegrationTest]

	at com.github.seregamorph.testsmartcontext.SmartDirtiesTestsHolder.getOrderState(SmartDirtiesTestsHolder.java:57)
	at com.github.seregamorph.testsmartcontext.SmartDirtiesTestsHolder.isLastClassPerConfig(SmartDirtiesTestsHolder.java:33)
	at com.github.seregamorph.testsmartcontext.SmartDirtiesContextTestExecutionListener.afterTestClass(SmartDirtiesContextTestExecutionListener.java:36)
	at org.springframework.test.context.TestContextManager.afterTestClass(TestContextManager.java:538)
	at org.springframework.test.context.junit.jupiter.SpringExtension.afterAll(SpringExtension.java:144)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
```

**Comment by seregamorph** [comment]
@cfraenkel thanks for your report, I will take a look

Also feel free to share your experience with the library, you are welcome

**Comment by cfraenkel** [comment]
Hi, thanks for your work on this. The library seems to be working well so far and I hope it can improve our build times and reduce a number of the issues we are encountering with spring context caching.
I've encountered some issues where we're currently using `@Nested` but my plan for now is to remove those usages.
Fyi, the build I'm applying it to is using gradle and spring boot 3.3.

**Comment by seregamorph** [comment]
The fix is now available on maven central https://github.com/seregamorph/spring-test-smart-context/releases/tag/v0.4
Thanks again and feel free to submit your findings/feature requests.

Also note, that `SmartDirtiesTestsSorter` methods are overridable in a project. You can find this instruction in the javadoc:
```
/**
 * The logic of this class can be customized via
 * <pre>
 * META-INF/services/com.github.seregamorph.testsmartcontext.SmartDirtiesTestsSorter
 * </pre>
 * defining subtype of this class overriding methods.
 */
public class SmartDirtiesTestsSorter {
```
So it was possible to have a temporary fix via SPI on your local codebase without a fork.

**Comment by cfraenkel** [comment]
Great, thanks for the fast merge and release.

**Comment by seregamorph** [comment]
@cfraenkel I've implemented the experimental support of Jupiter `@Nested` classes. It's available in the PR https://github.com/seregamorph/spring-test-smart-context/pull/9
Can you please do me a favor and try this change from the branch before it's released (there is no urgency).
Thanks in advance
